guard against sha error

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -68,6 +68,15 @@ jobs:
         if: runner.os == 'macOS'
         shell: bash
         run: |
+          # if file not found, exit with error
+          if [ ! -f "PubMan-${{ steps.calculate_version.outputs.version }}-arm64.dmg" ]; then
+              echo "Error: PubMan-${{ steps.calculate_version.outputs.version }}-arm64.dmg not found"
+              exit 1
+          fi
+          if [ ! -f "PubMan-${{ steps.calculate_version.outputs.version }}.dmg" ]; then
+              echo "Error: PubMan-${{ steps.calculate_version.outputs.version }}.dmg not found"
+              exit 1
+          fi
           echo "shaosxarm=$(shasum -a 256 PubMan-${{ steps.calculate_version.outputs.version }}-arm64.dmg | awk '{print $1}')" >> $GITHUB_OUTPUT
           echo "shaosxintel=$(shasum -a 256 PubMan-${{ steps.calculate_version.outputs.version }}.dmg | awk '{print $1}')" >> $GITHUB_OUTPUT
 
@@ -77,7 +86,11 @@ jobs:
         if: runner.os == 'Linux'
         shell: bash
         run: |
-          version=$(echo ${{ github.ref }} | sed 's|^refs/tags/v||')
+          # if file not found, exit with error
+          if [ ! -f "PubMan-${{ steps.calculate_version.outputs.version }}.AppImage" ]; then
+              echo "Error: PubMan-${{ steps.calculate_version.outputs.version }}.AppImage not found"
+              exit 1
+          fi
           echo "shalinux=$(shasum -a 256 PubMan-${{ steps.calculate_version.outputs.version }}.AppImage | awk '{print $1}')" >> $GITHUB_OUTPUT
 
   update-homebrew:
